[deps]
AbstractTrees = "1520ce14-60c1-5f80-bbc7-55ef81b5835c"
DifferentialEquations = "0c46a032-eb83-5123-abaf-570d42b7fbaa"
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
GR = "28b8d3ca-fb5f-59d9-8090-bfdbd6d07a71"
JuMP = "4076af6c-e467-56ae-b986-b466b2749572"
LaTeXStrings = "b964fa9f-0449-5b57-a5c2-d3ea65f4040f"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
MosekTools = "1ec41992-ff65-5c91-ac43-2df89e9693a4"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
QuadGK = "1fd47b50-473d-5c70-9696-f719f8f3bcdc"
SpecialFunctions = "276daf66-3868-5448-9aa4-cd146d93841b"

[compat]
AbstractTrees = "^0.2"
DifferentialEquations = "^6"
Documenter = "^0.22"
GR = "^0.4"
JuMP = "^0.19"
LaTeXStrings = "^1.0"
MosekTools = "^0.7"
Plots = "^0.25"
QuadGK = "^2"
SpecialFunctions = "^0.7"
